language: python
python:
  - "3.8.1"

# Install dependencies
before_install:
    - sudo apt-get install -y freetds-dev unixodbc unixodbc-dev

install: "pip install -r requirements.txt"

script: 
  - pylint --rcfile=pylintrc wmt_etl
  - python -m pytest wmt_etl/tests
